services:

  app:

    image: ${APP_IMAGE}

    pull_policy: always

    depends_on:
      postgres:
        condition: service_healthy

      redis:
        condition: service_healthy

    environment:
      SPRING_PROFILES_ACTIVE: prod

      DB_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}

      REDIS_HOST: redis
      REDIS_PORT: 6379

      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}

    ports:
      - "8080:8080"

    restart: unless-stopped

  postgres:

    image: postgres:17.6

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - postgres-data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]

      interval: 10s
      timeout: 5s
      retries: 5

    restart: unless-stopped

  redis:

    image: redis:8.4.0

    command:
      - redis-server
      - --appendonly
      - "yes"

    volumes:
      - redis-data:/data

    healthcheck:
      test:
        [
          "CMD",
          "redis-cli",
          "ping"
        ]

      interval: 10s
      timeout: 5s
      retries: 5

    restart: unless-stopped

volumes:

  postgres-data:

  redis-data:
