services:

  app:

    image: url-shortener:local

    container_name: url-shortener-app

    ports:
      - "8080:8080"

    environment:
      SPRING_PROFILES_ACTIVE: prod

      DB_URL: jdbc:postgresql://postgres:5432/url_shortener
      DB_USERNAME: postgres
      DB_PASSWORD: postgres

      REDIS_HOST: redis
      REDIS_PORT: 6379

      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: change-me

    depends_on:
      postgres:
        condition: service_healthy

      redis:
        condition: service_healthy

    restart: unless-stopped

  postgres:

    image: postgres:17.6

    container_name: url-postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: url_shortener
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:

    image: redis:8.4.0

    container_name: url-redis

    restart: unless-stopped

    ports:
      - "6379:6379"

    command:
      - redis-server
      - --appendonly
      - "yes"

    volumes:
      - redis-data:/data

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:

  postgres-data:

  redis-data:
